package:
  name: misc_scripts
  version: {{ environ['VERSION'] }}

source:
    path: ../bin

build:
  script_env:
   - VERSION
   - CONDA_BLD_PATH
   - TRAVIS_PULL_REQUEST
   - TRAVIS_PYTHON_VERSION

requirements:
  build:
      - python
      - argparse
      - flake8
      - future
      - pylint
      - pytest
      - scripttest
      - r-argparse
  run:
      - python
      - argparse
      - future
      - bedtools
      - pybedtools
      - r-argparse

about:
  home: https://travis-ci.org/dmaticzka/misc_scripts
  license: MIT
  summary: A random collection of bytes to handle this and that.
